acoustic: acoustic.onnx
augmentation_args:
  random_pitch_shifting:
    range:
    - -5.0
    - 5.0
fft_size: 2048
hidden_size: 384
hop_size: 512
languages: languages.json
max_depth: 0.7
mel_base: e
mel_fmax: 16000
mel_fmin: 40
mel_scale: slaney
num_mel_bins: 128
phonemes: phonemes.json
sample_rate: 44100
speakers:
- yunye
use_breathiness_embed: true
use_continuous_acceleration: true
use_energy_embed: false
use_key_shift_embed: true
use_lang_id: true
use_speed_embed: true
use_tension_embed: true
use_variable_depth: true
use_voicing_embed: true
vocoder: pc_nsf_hifigan_44.1k_hop512_128bin_2025.02
win_size: 2048
