hidden_size: 384
hop_size: 512
languages: ./languages.json
linguistic: ./linguistic.onnx
phonemes: ./phonemes.json
pitch: ./pitch.onnx
predict_breathiness: false
predict_dur: false
predict_energy: false
predict_tension: false
predict_voicing: true
sample_rate: 44100
speakers:
- zhibin-pop
use_continuous_acceleration: true
use_expr: true
use_lang_id: true
use_note_rest: true
variance: 260104_zhibin_club_pitch.variance.onnx
